name: "Deploy to pypi"
on:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install pipenv
          pipenv install --dev
      - name: Build dist
        run: |
          pipenv run python setup.py sdist bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
