name: "Deploy Test"
on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install pipenv
          pipenv install --dev
      - name: Build dist
        run: |
          pipenv run python setup.py sdist bdist_wheel
      - name: Upload packed files to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-all
          path: ./dist/*
