name: "Tests xdist"
on:
  push:
    branches:
      - master
    paths-ignore:
      - CHANGELOG.md
      - README.md
      - LICENSE
      - LICENSE.txt
      - release-process.rst
      - .gitignore
      - .coveragerc
      - .github/workflows/deploy.yml
      - .github/workflows/codeql-analysis.yml
      - .github/workflows/FUNDING.yml
      - setup.cfg
      - setup.py
      - webdriver_manager/__init__.py

  pull_request:
    branches:
      - master
    paths-ignore:
      - CHANGELOG.md
      - README.md
      - LICENSE
      - LICENSE.txt
      - release-process.rst
      - .gitignore
      - .coveragerc
      - .github/workflows/deploy.yml
      - .github/workflows/codeql-analysis.yml
      - .github/workflows/FUNDING.yml
      - setup.cfg
      - setup.py
      - webdriver_manager/__init__.py

jobs:
  test-xdist:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10' ]
        selenium-version: [ '4.1.0' ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install browsers on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install software-properties-common apt-transport-https wget curl
          sudo apt-get install chromium-browser
          chromium --version
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade flake8 setuptools wheel twine
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install selenium==${{ matrix.selenium-version }}
      - name: Run tests on Linux (with xvfb)
        if: runner.os == 'Linux'
        uses: GabrielBB/xvfb-action@v1
        env:
          WDM_LOG: ${{ matrix.wdm-log }}
          WORKERS: '2'
        with:
          run: |
            make xdisttest
      - name: List folders
        run: ls -la ~/.wdm
