name: "Tests"
on:
  push:
    branches:
      - master
    paths-ignore:
      - CHANGELOG.md
      - README.md
      - LICENSE
      - LICENSE.txt
      - release-process.rst
      - .gitignore
      - .coveragerc
      - .github/workflows/deploy.yml
      - .github/workflows/codeql-analysis.yml
      - .github/workflows/FUNDING.yml
      - setup.cfg
      - setup.py
      - webdriver_manager/__init__.py

  pull_request:
    branches:
      - master
    paths-ignore:
      - CHANGELOG.md
      - README.md
      - LICENSE
      - LICENSE.txt
      - release-process.rst
      - .gitignore
      - .coveragerc
      - .github/workflows/deploy.yml
      - .github/workflows/codeql-analysis.yml
      - .github/workflows/FUNDING.yml
      - setup.cfg
      - setup.py
      - webdriver_manager/__init__.py

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7' ]
        selenium-version: [ '3.141.0' ]
        os: [ windows-latest ]
        wdm-log: [ '' ]
        include:
          - python-version: '3.11'
            selenium-version: '4.6.0'
            os: ubuntu-latest
          - python-version: '3.11'
            selenium-version: '3.141.0'
            os: macos-latest
            wdm-log: '0'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install browsers on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install software-properties-common apt-transport-https wget curl

          wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
          sudo apt-get update && sudo apt install microsoft-edge-beta
          microsoft-edge --version

          wget -qO- https://deb.opera.com/archive.key | sudo apt-key add -
          sudo add-apt-repository "deb [arch=i386,amd64] https://deb.opera.com/opera-stable/ stable non-free"
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install opera-stable
          opera --version

          sudo apt-get install chromium-browser
          chromium --version
          
          sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
          sudo apt-get update
          sudo apt-get install brave-browser
          brave-browser --version
          sudo apt-get install -y tree cloc
      - name: Install browsers on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          choco install chromium opera brave --no-progress -y --force
          choco install tree cloc
      - name: Install browsers on MacOS
        if: startsWith(runner.os, 'macOS')
        run: |
          brew tap domt4/chromium
          brew update
          brew install --cask mac-chromium opera brave-browser
          brew install tree cloc
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade flake8 setuptools wheel twine
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Test the basic environment
        shell: bash
        run: |
          python -V
          pip --version
          pip list
          tree .
          cloc webdriver_manager
          cloc tests
      - name: Run tests on Linux (with xvfb)
        if: runner.os == 'Linux'
        env:
          WDM_LOG: ${{ matrix.wdm-log }}
        uses: coactions/setup-xvfb@v1
        with:
          run: |
            make unittest
      - name: Run tests on Windows (without xvfb)
        if: runner.os == 'Windows'
        run: |
          make unittest
      - name: Run tests on MacOS (without xvfb)
        if: startsWith(runner.os, 'macOS')
        run: |
          make unittest
      - name: Codecov Upload
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: ${{ matrix.os }}-py${{ matrix.python-version }}
          fail_ci_if_error: false

  test-negative:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7' ]
        selenium-version: [ '3.141.0' ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Uninstall browsers
        run: |
          sudo apt remove firefox google-chrome-stable -y
          sudo apt autoremove && sudo apt autoclean -y
          sudo apt clean
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade flake8 setuptools wheel twine
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install selenium==${{ matrix.selenium-version }}
      - name: Run tests on Linux (with xvfb)
        if: runner.os == 'Linux'
        uses: coactions/setup-xvfb@v1
        with:
          run: |
            make negatest
      - name: Codecov Upload
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: ${{ matrix.os }}-py${{ matrix.python-version }}
          fail_ci_if_error: false

  test-xdist:
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10' ]
        selenium-version: [ '4.1.0' ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install browsers on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install software-properties-common apt-transport-https wget curl
          sudo apt-get install chromium-browser
          chromium --version
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade flake8 setuptools wheel twine
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install selenium==${{ matrix.selenium-version }}
      - name: Run tests on Linux (with xvfb)
        if: runner.os == 'Linux'
        uses: coactions/setup-xvfb@v1
        env:
          WDM_LOG: ${{ matrix.wdm-log }}
        with:
          run: |
            make xdisttest
      - name: List folders
        run: ls -la ~/.wdm